import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored skill reference code — not ours to lint.
    ".agents/**",
    ".claude/**",
    // The Studio is its own workspace with its own tooling.
    "studio/**",
    // Generated by Sanity TypeGen.
    "sanity.types.ts",
  ]),
]);

export default eslintConfig;
