/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type VideoChunk = {
  _type: "videoChunk";
  startSeconds?: number;
  text?: string;
};

export type VideoChapter = {
  _type: "videoChapter";
  startSeconds?: number;
  label?: string;
};

export type LessonResource = {
  _type: "lessonResource";
  type?: "documentation" | "article" | "code" | "download" | "video" | "link";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "layers"
    | "database"
    | "gauge"
    | "cloud"
    | "shield"
    | "zap"
    | "git-branch"
    | "terminal"
    | "code"
    | "workflow"
    | "rocket"
    | "puzzle"
    | "sparkles";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type CourseModule = {
  _type: "courseModule";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  url?: string;
  provider?: "youtube" | "vimeo" | "bunny";
  title?: string;
  chapters?: Array<
    {
      _key: string;
    } & VideoChapter
  >;
  chunks?: Array<
    {
      _key: string;
    } & VideoChunk
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  durationSeconds?: number;
  notes?: BlockContent;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & LessonResource
  >;
  freePreview?: boolean;
  studentCount?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  outcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & CourseModule
  >;
  popular?: boolean;
  studentCount?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: BlockContent;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | VideoChunk
  | VideoChapter
  | LessonResource
  | LearningOutcome
  | LessonReference
  | CourseModule
  | Video
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: COURSES_CATALOG_QUERY
// Query: *[_type == "course" && defined(slug.current)]  | order(popular desc, title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},  "categoryTitle": category->title,  "instructorName": instructor->name,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds)  }
export type COURSES_CATALOG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  categoryTitle: string | null;
  instructorName: string | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDurationSeconds: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},  "categoryTitle": category->title,  "instructorName": instructor->name,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds),    outcomes[] {      _key,      icon,      title,      description    },    instructor->{      _id,      name,      "slug": slug.current,      expertise,      photo {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }}    },    category->{      _id,      title,      "slug": slug.current    },    modules[] {      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        summary,        durationSeconds,        freePreview      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  categoryTitle: string | null;
  instructorName: string | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalDurationSeconds: number | null;
  outcomes: Array<{
    _key: string;
    icon:
      | "cloud"
      | "code"
      | "database"
      | "gauge"
      | "git-branch"
      | "layers"
      | "puzzle"
      | "rocket"
      | "shield"
      | "sparkles"
      | "terminal"
      | "workflow"
      | "zap"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    expertise: Array<string> | null;
    photo: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      summary: string | null;
      durationSeconds: number | null;
      freePreview: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    videoUrl,    durationSeconds,    freePreview,    studentCount,    poster {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},    notes,    keyPoints,    proTip,    resources[] {      _key,      type,      title,      description,      url    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  videoUrl: string | null;
  durationSeconds: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  poster: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  notes: BlockContent | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type:
      | "article"
      | "code"
      | "documentation"
      | "download"
      | "link"
      | "video"
      | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_COURSE_CONTEXT_QUERY
// Query: *[_type == "course" && references($lessonId)][0] {    _id,    title,    "slug": slug.current,    level,    coverImage {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},    instructor->{      _id,      name,      "slug": slug.current,      photo {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }}    },    modules[] {      _key,      title,      lessons[]->{        _id,        title,        "slug": slug.current,        durationSeconds,        freePreview      }    }  }
export type LESSON_COURSE_CONTEXT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  coverImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      durationSeconds: number | null;
      freePreview: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)].slug.current
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    expertise,    bio,    photo {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},    "courses": *[_type == "course" && instructor._ref == ^._id]      | order(popular desc, title asc) {          _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},  "categoryTitle": category->title,  "instructorName": instructor->name,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds)      }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  expertise: Array<string> | null;
  bio: BlockContent | null;
  photo: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    categoryTitle: string | null;
    instructorName: string | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalDurationSeconds: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: SEARCH_LESSONS_BY_IDS_QUERY
// Query: *[_type == "lesson" && _id in $ids && defined(slug.current)] {    _id,    title,    "slug": slug.current,    summary,    keyPoints,    durationSeconds,    videoUrl,    poster {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      "slug": slug.current,      coverImage {  "alt": alt,  asset->{    _id,    url,    metadata {lqip, dimensions}  }},      modules[] {        _key,        title,        "lessons": lessons[]->{          _id,          title,          "slug": slug.current,          durationSeconds        }      }    }  }
export type SEARCH_LESSONS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  keyPoints: Array<string> | null;
  durationSeconds: number | null;
  videoUrl: string | null;
  poster: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    coverImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: string | null;
        durationSeconds: number | null;
      }> | null;
    }> | null;
  } | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: SEARCH_VIDEO_MOMENTS_QUERY
// Query: *[_type == "video" && url in $urls] {    url,    chapters[] {      startSeconds,      label    },    "chunkSeconds": chunks[].startSeconds  }
export type SEARCH_VIDEO_MOMENTS_QUERY_RESULT = Array<{
  url: string | null;
  chapters: Array<{
    startSeconds: number | null;
    label: string | null;
  }> | null;
  chunkSeconds: Array<number | null> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)]\n  | order(popular desc, title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n  "categoryTitle": category->title,\n  "instructorName": instructor->name,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n\n  }\n': COURSES_CATALOG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n  "categoryTitle": category->title,\n  "instructorName": instructor->name,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n,\n    outcomes[] {\n      _key,\n      icon,\n      title,\n      description\n    },\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      expertise,\n      photo {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n}\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    modules[] {\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        summary,\n        durationSeconds,\n        freePreview\n      }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    videoUrl,\n    durationSeconds,\n    freePreview,\n    studentCount,\n    poster {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n    notes,\n    keyPoints,\n    proTip,\n    resources[] {\n      _key,\n      type,\n      title,\n      description,\n      url\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && references($lessonId)][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    level,\n    coverImage {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n}\n    },\n    modules[] {\n      _key,\n      title,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        durationSeconds,\n        freePreview\n      }\n    }\n  }\n': LESSON_COURSE_CONTEXT_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)].slug.current\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    expertise,\n    bio,\n    photo {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n    "courses": *[_type == "course" && instructor._ref == ^._id]\n      | order(popular desc, title asc) {\n        \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n  "categoryTitle": category->title,\n  "instructorName": instructor->name,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalDurationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n\n      }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "lesson" && _id in $ids && defined(slug.current)] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    keyPoints,\n    durationSeconds,\n    videoUrl,\n    poster {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage {\n  "alt": alt,\n  asset->{\n    _id,\n    url,\n    metadata {lqip, dimensions}\n  }\n},\n      modules[] {\n        _key,\n        title,\n        "lessons": lessons[]->{\n          _id,\n          title,\n          "slug": slug.current,\n          durationSeconds\n        }\n      }\n    }\n  }\n': SEARCH_LESSONS_BY_IDS_QUERY_RESULT;
    '\n  *[_type == "video" && url in $urls] {\n    url,\n    chapters[] {\n      startSeconds,\n      label\n    },\n    "chunkSeconds": chunks[].startSeconds\n  }\n': SEARCH_VIDEO_MOMENTS_QUERY_RESULT;
  }
}
